CREATE OR REPLACE VIEW RES AS
SELECT GROUPID,COUNT(*) AS PEOPLE
FROM JOIN
GROUP BY GROUPID;
SELECT DISTINCT U.USERID,U.NAME, U.NAME
FROM LINKEDINUSER U, RES R, JOIN G
WHERE  G.USERID=U.USERID AND R.GROUPID=G.GROUPID AND R.PEOPLE>10 AND U.USERID NOT IN 
(SELECT P2.SENDERID FROM POST P2 WHERE P2.DATETIME>SYSDATE-7);