CREATE OR REPLACE VIEW CNUM AS
SELECT U.NAME, count(*) as times
FROM lINKEDINUSER U,LINKEDINCOMMENT C,POST P, lINKEDINUSER UI
WHERE U.USERID=C.POSTID AND C.POSTID=P.POSTID AND UI.NAME='Jackie Chan' AND UI.USERID=P.SENDERID
GROUP BY U.NAME ORDER BY times desc;

SELECT NAME
FROM CNUM 
WHERE times >2;





