SELECT P.CONTENT
FROM lINKEDINUSER U,POST P
WHERE U.NAME='Jackie Chan' AND U.USERID=P.SENDERID AND to_char(P.DATETIME,'Mon')='Jan' AND P.POSTID NOT IN
(SELECT PO.POSTID
FROM POST PO, ATTACH A
WHERE PO.POSTID=A.PID);